name: .NET

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v3
    
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: |
          dotnet restore
      
      - name: Build
        run: |
          dotnet build --configuration Release --no-restore
      
      - name: Pack
        run: |
          dotnet pack --configuration Release

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/seiyainoueM/index.json" -n "github" -u seiyainoueM -p ${{secrets.GH_PACKAGES_PAT}} --store-password-in-clear-text
          dotnet nuget push "bin/Release/*.nupkg" --api-key ${{secrets.GH_PACKAGES_PAT}} --source "github" --skip-duplicate

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.81.3
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.GH_PACKAGES_PAT }}