name: .NET

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v2
    
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: |
          dotnet restore
      
      - name: Build
        run: |
          dotnet build --configuration Release --no-restore
      
      - name: Pack
        run: |
          dotnet pack --configuration Release

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget add source --username seiyainoueM --password ${{ secrets.GH_PACKAGES_PAT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/seiyainoueM/index.json"
          dotnet nuget push "bin/Release/*.nupkg" --api-key ${{secrets.GH_PACKAGES_PAT}} --source "github" --skip-duplicate